---
title: "Workshop: Artificial neural networks in R with Keras and TensorFlow"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

By [Leon Eyrich Jessen](https://leonjessen.github.io/)

This is the GitHub repository for the Workshop: "Artificial neural networks in R with Keras and TensorFlow" at [The second annual R/Pharma conference held August 21, 22, and 23, 2019, Harvard University, Cambridge, US](http://rinpharma.com/)

## Introduction

Everything you need to know can be found at the RStudio page on [R Interface to TensorFlow](https://tensorflow.rstudio.com/). Here you can also find more on [keras](https://tensorflow.rstudio.com/keras/), with [examples](https://tensorflow.rstudio.com/keras/articles/examples/) and [invited blog posts](https://blogs.rstudio.com/tensorflow/)

## Getting started

Keras installation instructions can be found [here](https://tensorflow.rstudio.com/keras/#getting-started)

## Schedule Wednesday August 21st 2019

At the workshop, the aim is to briefly introduce the participants to the theory of artificial neural networks and the follow this up with a series of interchanging brief talks and longer exercises aiming at building inital hands on experience. The schedule is as follows:

_(Please note the html preview currently seem not be functioning. All slides are available under 'Talks' in your RStudio session. Left-click on the .html file and choose 'View in Web Browser')_

- 08.00 - 08.15 [Brief talk: Introduction to Artificial Neural Networks](http://htmlpreview.github.io/?https://github.com/leonjessen/RPharma2019/blob/master/Talks/01_introduction_to_artificial_neural_networks.html)
- 08.15 - 08.40 [Exercise: Prototyping an ANN in R](Exercises/01_ann_prototype.md)
- 08.40 - 08.45 [Brief talk: Introduction to TensorFlow/Keras in R 1](http://htmlpreview.github.io/?https://github.com/leonjessen/RPharma2019/blob/master/Talks/02_introduction_to_keras_1.html)
- 08.45 - 09.00 [Exercise: TensorFlow Playground](Exercises/02_tensorflow_playground.md)
- 09.00 - 09.15 [Brief talk: Introduction to TensorFlow/Keras in R 2](http://htmlpreview.github.io/?https://github.com/leonjessen/RPharma2019/blob/master/Talks/03_introduction_to_keras_2.html)
- 09.15 - 09.45 [Exercise: Hello Keras (Classification)](Exercises/03_hello_keras.md)
- 09.45 - 10.00 [Brief talk: Session 1 Summary and Q&A](http://htmlpreview.github.io/?https://github.com/leonjessen/RPharma2019/blob/master/Talks/04_session_1_summary.html)

- 10.00 - 10.20 Coffee Break

- 10.20 - 10.45 [Brief talk: A bit more on Keras](http://htmlpreview.github.io/?https://github.com/leonjessen/RPharma2019/blob/master/Talks/05_a_bit_more_on_keras.html)
- 10.45 - 11.15 [Exercise: Predicting Price (regression)](Exercises/04_diamonds_regression.md)
- 11.15 - 11.45 [Exercise: Deep Learning for Cancer Immunotherapy](Exercises/05_deep_learning_for_cancer_immunotherapy.md)
- 11.45 - 12.00 [Brief talk: Session 2 Summary and Q&A](http://htmlpreview.github.io/?https://github.com/leonjessen/RPharma2019/blob/master/Talks/06_session_2_summary.html)

## Additional Resources

### Web

* [R Interface to TensorFlow](https://tensorflow.rstudio.com/)
* [R interface to Keras](https://tensorflow.rstudio.com/keras/)
* [Keras Examples](https://tensorflow.rstudio.com/keras/articles/examples/)
* [Invited Blog Posts](https://blogs.rstudio.com/tensorflow/)
* [Learning Resources](https://tensorflow.rstudio.com/learn/resources.html)
* [RStudio Community](https://community.rstudio.com/)
* [RStudio Cloud](https://rstudio.cloud/)
* [Deep Learning with Keras Cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/keras.pdf)

### Books

* [Deep Learning with R](https://www.manning.com/books/deep-learning-with-r)
* [Free: Deep Learning book](https://www.deeplearningbook.org/)
* [Free: R for Data Science by Garrett Grolemund and Hadley Wickham](https://r4ds.had.co.nz/)
* [Free: ModernDive - An Introduction to Statistical and Data Sciences via R](https://moderndive.com/)
